name: Run ADVANCED HEADSHOT Opportunity Hunter

on:
  schedule:
    - cron: '0 */12 * * *'  # Run every 12 hours (less frequent due to more intensive processing)
  workflow_dispatch:

jobs:
  headshot:
    runs-on: ubuntu-latest
    timeout-minutes: 45 # Increased timeout for potentially longer run

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9' # spaCy works well with 3.9+

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 feedparser spacy==3.7.2 # Pinned spaCy for model compatibility
          # Download the spaCy English model
          python -m spacy download en_core_web_sm

      - name: Create data directory
        run: mkdir -p data

      - name: Download previous database
        uses: actions/download-artifact@v4
        with:
          name: headshot-database
          path: data/
        continue-on-error: true

      - name: Run HEADSHOT Agent
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          # GITHUB_TOKEN is automatically available to the runner
        run: python headshot_agent.py

      - name: Upload database
        uses: actions/upload-artifact@v4
        with:
          name: headshot-database
          path: data/headshot_vault.db
          retention-days: 90

      - name: Upload opportunity reports
        uses: actions/upload-artifact@v4
        with:
          name: headshot-opportunities
          path: data/headshot_opportunities.csv
          retention-days: 90
